version: '2'
services:
  master:
    image: firecamp/spark
    container_name: firecamp-spark-master
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
       MASTER: spark://master:7077
       SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 28080:8080
    volumes:
      - $PWD/work/project-conf/spark:/conf
      - $PWD/work/:/home/jovyan/work
    networks:
      - firecamp-cluster
    links:
      - cassandra

  worker-1:
    image: firecamp/spark
    container_name: firecamp-spark-worker-1
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_CONF_DIR: /conf
    links:
      - master
    expose:
      - 8081
    volumes:
      - $PWD/work/project-conf/spark:/conf
      - $PWD/work/:/home/jovyan/work
    networks:
      - firecamp-cluster

  worker-2:
    image: firecamp/spark
    container_name: firecamp-spark-worker-2
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_CONF_DIR: /conf
    links:
      - master
    expose:
      - 8081
    volumes:
      - $PWD/work/project-conf/spark:/conf
      - $PWD/work/:/home/jovyan/work

    networks:
      - firecamp-cluster

  worker-3:
    image: firecamp/spark
    container_name: firecamp-spark-worker-3
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_CONF_DIR: /conf
    links:
      - master
    expose:
      - 8081
    volumes:
      - $PWD/work/project-conf/spark:/conf
      - $PWD/work/:/home/jovyan/work

    networks:
      - firecamp-cluster

  spark-ui-proxy:
    image: yanndegat/spark-ui-proxy
    container_name: firecamp-spark-proxy
    command: master:8080 9999
    ports:
      - 8080:9999
    networks:
      - firecamp-cluster

  cassandra:
     image: cassandra:latest
     hostname: cassandra
     container_name: firecamp-cassandra-1
     command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
     environment:
         - CASSANDRA_SEEDS=cassandra-1,cassandra-2, #cassandra-3
         - JVM_OPTS= $JVM_OPTS -Xms1g -Xmx1g
     expose:
         - 7000
         - 7001
         - 7199
         - 9042
         - 9160
     ports:
         - 9042:9042
     networks:
         - firecamp-cluster

  cassandra-2:
     image: cassandra:latest
     container_name: firecamp-cassandra-2
     command: /bin/bash -c "sleep 10 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
     environment:
         - CASSANDRA_SEEDS=cassandra-1,cassandra-2 #,cassandra-3
         - JVM_OPTS= $JVM_OPTS -Xms1g -Xmx1g
     expose:
         - 7000
         - 7001
         - 7199
         - 9042
         - 9160
     ports:
         - 9044:9042
     links:
         - cassandra
     networks:
         - firecamp-cluster

  # cassandra-3:
  #    image: cassandra:latest
  #    container_name: firecamp-cassandra-3
  #    command: /bin/bash -c "sleep 20 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
  #    environment:
  #        - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
  #        - JVM_OPTS= $JVM_OPTS -Xms2g -Xmx2g
  #    expose:
  #        - 7000
  #        - 7001
  #        - 7199
  #        - 9042
  #        - 9160
  #    ports:
  #        - 9043:9042
  #    links:
  #        - cassandra
  #    networks:
  #        - firecamp-cluster

  jupyter:
    image: firecamp/jupyter
    container_name: firecamp-jupyter
    hostname: jupyter
    environment:
      SPARK_CONF_DIR: /usr/local/spark/conf
    links:
      - master
      - cassandra
    ports:
      - 8888:8888
    volumes:
      - $PWD/work/project-conf/spark:/usr/local/spark/conf
      - $PWD/work:/home/jovyan/work
    networks:
      - firecamp-cluster
    #command: bash -c "pip install -r /home/jovyan/work/project-conf/python/requirements.txt && sh /home/jovyan/work/project-conf/python/additional_setup.txt && jupyter notebook"
    command: bash -c "pip install -r /home/jovyan/work/project-conf/python/requirements.txt && jupyter notebook"

networks:
  firecamp-cluster:
